import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  shell: { flex: 1, flexDirection: 'row', backgroundColor: colors.bg },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bg },
  sidebar: {
    width: 232,
    backgroundColor: colors.surface,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    padding: 12,
    zIndex: 3,
  },
  sidebarDesktop: { minHeight: '100%' },
  sidebarCollapsed: { width: 72 },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  brandText: { color: colors.primaryDark, fontSize: 18, fontWeight: '900' },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  sidebarNav: { flex: 1 },
  sidebarNavContent: { paddingBottom: 18, gap: 5 },
  navItem: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 10, paddingHorizontal: 11, borderRadius: 8 },
  navItemCollapsed: { justifyContent: 'center', gap: 0 },
  navItemActive: { backgroundColor: colors.primary },
  navLabel: { color: colors.primaryDark, fontWeight: '800' },
  navLabelActive: { color: '#fff' },
  main: { flex: 1, minWidth: 0 },
  topbar: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  heading: { color: colors.primaryDark, fontSize: 22, fontWeight: '900' },
  subheading: { color: colors.textMuted, marginTop: 2 },
  adminSection: { gap: 14 },
  adminSubtitle: { color: colors.textMuted, lineHeight: 20, marginTop: -8 },
  refreshButton: { minHeight: 40, paddingVertical: 8, paddingHorizontal: 12 },
  scroll: { flex: 1 },
  content: { padding: 18, paddingBottom: 60 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
  metricCard: {
    flexGrow: 1,
    flexBasis: 170,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 14,
  },
  metricTitle: { color: colors.textMuted, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  metricValue: { color: colors.primaryDark, fontSize: 24, fontWeight: '900', marginTop: 8 },
  metricMoney: { color: colors.primary },
  metricDanger: { color: colors.danger },
  twoColumn: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  panel: {
    width: '100%',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
    minWidth: 0,
    maxHeight: 1200,
  },
  twoColumnPanel: {
    flexGrow: 1,
    flexBasis: 360,
    width: 'auto',
  },
  panelScroll: {
    flex: 1,
  },
  panelTitle: { color: colors.primaryDark, fontSize: 17, fontWeight: '900', marginBottom: 10 },
  searchRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10, flexWrap: 'wrap' },
  searchButton: { marginBottom: 16, minWidth: 120 },
  helpText: { color: colors.textMuted, lineHeight: 19, marginBottom: 8 },
  dataRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingVertical: 11,
  },
  userTableHeader: {
    flexDirection: 'row',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingVertical: 9,
    alignItems: 'center',
  },
  userTableRow: {
    flexDirection: 'row',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingVertical: 10,
    alignItems: 'center',
  },
  userTableHeadText: {
    color: colors.primaryDark,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  userTableText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
    minWidth: 0,
  },
  userEmailCell: { flex: 2.2, minWidth: 120 },
  userNameCell: { flex: 1.5, minWidth: 96 },
  userPhoneCell: { flex: 1.1, minWidth: 88 },
  userCreditsCell: { flex: 0.7, minWidth: 52 },
  userJoinedCell: { flex: 1, minWidth: 82 },
  rowTitle: { color: colors.text, fontWeight: '900', flexShrink: 1, flexWrap: 'wrap' },
  meta: { color: colors.textMuted, fontSize: 12, marginTop: 3, flexShrink: 1, flexWrap: 'wrap' },
  bodyText: { color: colors.text, lineHeight: 20, marginTop: 4, flexShrink: 1, flexWrap: 'wrap' },
  codeText: { color: colors.text, fontFamily: 'monospace', fontSize: 12, backgroundColor: '#F7F9F4', padding: 10, borderRadius: 8, marginTop: 8 },
  pill: {
    color: colors.primary,
    backgroundColor: '#F1F4F2',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'capitalize',
  },
  pillGood: { color: colors.primary, backgroundColor: '#EAF4EE' },
  pillDanger: { color: colors.danger, backgroundColor: '#FCEDEF' },
  amount: { color: colors.primary, fontWeight: '900', fontSize: 18 },
  debit: { color: colors.danger },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  formField: { minWidth: 220, flexGrow: 1, flexBasis: 220 },
  buttonRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  filterPanel: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#F7F9F4',
  },
  filterInput: { minWidth: 160 },
  filterSelect: { minWidth: 190, flexGrow: 1, flexBasis: 190 },
  clearFilterButton: { minHeight: 42, marginTop: 22, paddingVertical: 8 },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  detailItem: { flexGrow: 1, flexBasis: 180, borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 10, minWidth: 0 },
  detailLabel: { color: colors.textMuted, fontSize: 12, fontWeight: '800', flexShrink: 1 },
  detailValue: { color: colors.text, fontWeight: '800', marginTop: 4, flexShrink: 1, flexWrap: 'wrap' },
  sectionLabel: { color: colors.primaryDark, fontWeight: '900', marginTop: 14, marginBottom: 6 },
  emptyText: { color: colors.textMuted, lineHeight: 20 },
  errorText: { color: colors.danger, fontWeight: '700', lineHeight: 20, marginTop: 10 },
  adminLoginBox: { marginTop: 16, maxWidth: 440 },
  settingsStack: {
    width: '100%',
    gap: 14,
  },
  settingsPanel: {
    width: '100%',
    flexGrow: 0,
    flexBasis: 'auto',
    alignSelf: 'stretch',
    marginBottom: 0,
  },
  appSettingsPanel: {
    marginTop: 4,
  },
  settingsIntro: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    padding: 16,
  },
  settingsIntroTitle: { color: '#fff', fontSize: 20, fontWeight: '900', marginBottom: 6 },
  settingsIntroText: { color: '#EAF2EE', lineHeight: 20 },
  packageGrid: { gap: 10, marginTop: 10 },
  packageAdminCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#F7F9F4',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  packageAdminMain: { flex: 1, minWidth: 220 },
  packageAdminTitle: { color: colors.primaryDark, fontSize: 16, fontWeight: '900', marginBottom: 2 },
  packageAdminActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    flexWrap: 'wrap',
    flexShrink: 1,
  },
  packageActionButton: { minHeight: 38, paddingVertical: 7, paddingHorizontal: 10 },
  packageStatus: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '900',
  },
  packageStatusActive: { color: colors.primary, backgroundColor: '#EAF4EE' },
  packageStatusInactive: { color: colors.textMuted, backgroundColor: '#ECEDEA' },
  generatedIdBox: {
    minWidth: 220,
    flexGrow: 1,
    flexBasis: 220,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    backgroundColor: '#F7F9F4',
  },
  generatedIdLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 6,
  },
  generatedIdValue: {
    color: colors.primaryDark,
    fontSize: 16,
    fontWeight: '900',
  },
  generatedIdHelp: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 },
  previewBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    backgroundColor: '#F7F9F4',
  },
  editActionPanel: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: 14,
    paddingTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    backgroundColor: colors.surface,
  },
  editActionButton: { minWidth: 140 },
  settingsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 14 },
  settingsBox: {
    flexGrow: 1,
    flexBasis: 260,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#F7F9F4',
  },
});
