import type { ClassLevel } from './lessonPlan';

export interface SchemeWeekEntry {
  strand?: string;
  subStrand?: string;
  contentStandardCode?: string;
  contentStandard?: string;
  indicatorCode?: string;
  indicator?: string;
  topic?: string;
  resources?: string[];
  exemplars?: string[];
  sourcePage?: number;
}

/** A single week row in a Scheme of Learning / Scheme of Work. */
export interface SchemeWeek extends SchemeWeekEntry {
  week: number;
  theme?: string;
  entries?: SchemeWeekEntry[];
  matchedCurriculumTerm?: string;
  matchConfidence?: number;
  uploadedTopic?: string;
}

/** Termly Scheme of Learning — uploaded by the teacher (PDF/text) or AI-generated. */
export interface SchemeOfLearning {
  id?: string;
  title: string;
  subject: string;
  classLevel: ClassLevel;
  term: string;
  academicYear?: string;
  source?: 'mapped' | 'ai' | 'uploaded' | 'reconciled';
  parserMetadata?: {
    warnings?: string[];
    confidence?: number;
    detectedMetadata?: {
      subject?: string;
      classLevel?: string;
      term?: string;
    };
  };
  /** Source PDF stored in Supabase storage; key path */
  sourceFileKey?: string;
  /** Parsed / generated week-by-week breakdown */
  weeks: SchemeWeek[];
  createdAt?: string;
}

/** Scheme of Work — same shape but generated by the AI. */
export type SchemeOfWork = SchemeOfLearning;

export interface SchemeGenerationInput {
  subject: string;
  classLevel: ClassLevel;
  term: string;
  academicYear?: string;
  numberOfWeeks?: number;
  /** Free-form curriculum notes / topics to cover */
  notes?: string;
}
